@startuml

title Essential Reposition Meta-Model

Customer_Journey --> Customer_Journey_Phase: Has
Customer_Journey_Phase --> Value_Stage: Relates

Value_Stream --> Value_Stage: Contains
Value_Stage --> Value_Stream: BelongTo

Value_Stage --> Business_Capability: Requires

Business_Capability --> Business_Process: Realized_By
Business_Process --> Business_Capability: Realizes

Business_Capability --> Information_Concept: Supported_By
Information_Concept --> Business_Capability: Supporting

Business_Capability --> Business_Capability: Parent/Child

Business_Process --> Physical_Process: Performed_By
Physical_Process --> Business_Process: Performing

Business_Process --> Business_Process: Parent/Child

Business_Process --> Business_Process_Flow: Defining

Business_Process_Flow --> Business_Activity: Contains

Business_Activity --> Physical_Activity: Performed_By_Organization
Physical_Activity <-- Application_Provider: Supporting
Physical_Activity --> Group_Actor: Performed_By
Physical_Activity --> Site: Performed_At

Physical_Process --> Application_Provider: Supported_By
Application_Provider --> Physical_Process: Supporting

Physical_Process --> Customer_Journey_Phase: Supporting

Product_Concept --> Product_Type: Realized_By
Product_Type --> Product_Concept: Realizes
Product --> Product_Type: Instance_Of

Product_Type --> Business_Process: Produced_By

Application_Provider <-- Supplier
Application_Provider --> Group_Business_Role: Stakeholder
Application_Provider --> Site: Usage_Location
Application_Provider --> Static_Application_Provider_Architecture: Application_Dependencies

Information_Domain --> Information_Concept: Contains
Information_Concept --> Data_Subject: Supported_By
Data_Subject --> Information_Concept: Supporting
Data_Subject --> Data_Object: Realized_By
Data_Object --> Data_Subject: Realizes
Data_Object --> Data_Object_Attribute: Contains

Static_Application_Provider_Architecture --> Information_Representation: Uses
Information_Representation --> Static_Application_Provider_Architecture: Used_By
Information_Representation --> Information_Object: Implementing
Information_Object <-- Data_Object: Supporting

Data_Object -up-> Application_Provider: System_Of_Record

Project --> Program: Child_Of
Program --> Project: Parent_Of

Project -right-> Application_Provider: ChangesOn

' Business Layer

Business_Capability: Name (BA Team)
Business_Capability: Description (BA Team)

' Application Layer

Application_Provider: Name (PlanView OutcomeName_APMID)
Application_Provider: Delivery Model (PlanView)
Application_Provider: Lifecycle Status (PlanView Outcome_Stage)
Application_Provider: Usage Locations (Archi Modeling)
Application_Provider: Reusable Justification
Application_Provider: Supplier (PlanView Software_Vendor)

' Information Layer

Information_Domain: DRM Level 0
Information_Concept: DRM Level 1
Data_Subject: DRM Level 2
Data_Object: DRM Level 3
Data_Object_Attribute: DRM Business Vocabulary

' EA Support Layer

' EA Support > Change Management

Project: ProjectName_PPMID (PlanView)
Project: Description (PlanView)
Project: Lifecycle Status (PlanView)
Project: Drivers For Change (DA)
Project: Initiative Objectives (DA)
Project: Provided Value
Project: Strategic Plans Supported (PlanView)
Project: Planned Changes

Program: Name_InitiativeID (PlanView)

' EA Support > Utilities
Supplier: Name
Supplier: Description
Supplier: Supplier URL

footer Version 3, date 2024/08/12

@enduml